### PR TITLE
Dependency Injection

### PR DESCRIPTION
**Pull request by Kittycraft**
# Note
This is not a final stable build. This pull request is to go over the changes as they as discussed/modified and eventually if things work out, merge.

 # Changes (so far)
 - Auto formatted everything
 - Started adding dependency injection
 - Wrote new sub-command layout

 ### Dependency Injection
The dependency injection is only on about half of the items it needs to be on so far. As the command system is being finished, the dependency injection will slowly be refined and added to the remaining parts.

 ### New Sub-command Layout
The main feature being added is the new way of doing sub commands. It dramatically cuts down the length of files and makes them much more readable. They now contain important information to help the writer more easily see what they are trying to do such as the description, aliases, and what ranks are allowed to use the command. The commands FactionPlayerCommand class will automatically require the command sender to be in game, in a faction, and will check that their rank in the faction is sufficient (Or if they are in admin mode). If the player does not meet the requirements the command is not run and they are sent the corresponding error message. Also thanks to dependency injection and reflecting, a new command only needs to be in the commands package, be annotated with @Subcommand, and it will automatically be added to the list of subcommands. There will also be other alternatives to FactionPlayerCommand (**Possibly converted to an annotation instead for convenience**) in order to fit the needs of the command.
Using the example of /f disband: 
 ##### Before
```java
public class DisbandCommand implements CommandExecutor
{
    @Override
    public CommandResult execute(CommandSource source, CommandContext context) throws CommandException
    {
        if(source instanceof Player)
        {
            Player player = (Player)source;

            Optional<Faction> optionalPlayerFaction = FactionLogic.getFactionByPlayerUUID(player.getUniqueId());

            if(optionalPlayerFaction.isPresent())
            {
                Faction playerFaction = optionalPlayerFaction.get();
                if(EagleFactions.AdminList.contains(player.getUniqueId()))
                {
                    boolean didSucceed = FactionLogic.disbandFaction(playerFaction.Name);

                    if (didSucceed)
                    {
                        player.sendMessage(Text.of(PluginInfo.PluginPrefix,TextColors.GREEN, PluginMessages.FACTION_HAS_BEEN_DISBANDED));

                        if(EagleFactions.AutoClaimList.contains(player.getUniqueId())) EagleFactions.AutoClaimList.remove(player.getUniqueId());
                    }
                    else
                    {
                        player.sendMessage(Text.of(PluginInfo.PluginPrefix, TextColors.RED, PluginMessages.SOMETHING_WENT_WRONG));
                    }

                    return CommandResult.success();
                }

                if(playerFaction.Leader.equals(player.getUniqueId().toString()))
                {
                    try
                    {
                        boolean didSucceed = FactionLogic.disbandFaction(playerFaction.Name);

                        if (didSucceed)
                        {
                            player.sendMessage(Text.of(PluginInfo.PluginPrefix,TextColors.GREEN, PluginMessages.FACTION_HAS_BEEN_DISBANDED));

                            if(EagleFactions.AutoClaimList.contains(player.getUniqueId())) EagleFactions.AutoClaimList.remove(player.getUniqueId());
                        }
                        else
                        {
                            player.sendMessage(Text.of(PluginInfo.PluginPrefix, TextColors.RED, PluginMessages.SOMETHING_WENT_WRONG));
                        }

                        return CommandResult.success();
                    }
                    catch (Exception exception)
                    {
                        exception.printStackTrace();
                    }
                }
                else
                {
                    player.sendMessage(Text.of(PluginInfo.ErrorPrefix, PluginMessages.YOU_MUST_BE_THE_FACTIONS_LEADER_TO_DO_THIS));
                }
            }
            else
            {
                player.sendMessage(Text.of(PluginInfo.ErrorPrefix, TextColors.RED, PluginMessages.YOU_MUST_BE_IN_FACTION_IN_ORDER_TO_USE_THIS_COMMAND));
            }
        }
        else
        {
            source.sendMessage (Text.of (PluginInfo.ErrorPrefix, TextColors.RED, PluginMessages.ONLY_IN_GAME_PLAYERS_CAN_USE_THIS_COMMAND));
        }

        return CommandResult.success();
    }
}
```

 ##### After
```java
@Singleton
@RequiredRank(minimumRank = FactionMemberType.LEADER)
@Subcommand(aliases = {"disband"}, description = "Disband Faction Command", permission = PluginPermissions.DisbandCommand)
public class DisbandCommand extends FactionPlayerCommand
{
    @Inject
    public DisbandCommand(FactionsCache cache, Settings settings, FactionLogic factionLogic, @Named("factions") Logger logger)
    {
        super(cache, settings, factionLogic, logger);
    }

    @Override
    protected boolean executeCommand(Player player, Faction faction, CommandContext context)
    {
        faction.forEachMember(e -> EagleFactions.AutoClaimList.remove(UUID.fromString(e)));
        cache.removeFaction(faction.Name);
        return true;
    }
}
```

 #### Minor note
My goal with this project is to turn eagle factions into a versatile factions/war/protection plugin. Possibly allow a server admin through the console to do "/f setup [factions/war/protection]". I think that this is a goal which can be achieved over time provided that work is done at a reasonable rate.
 * Factions
   * Contains all of the same commands as massivecraft factions (give or take a few) as well as the same look and feel to produce a traditional factions experience
 * War
   * More similar to how it is now with the ability to /f attack factions, claim land(that can be modified by enemies when the faction is online), and form long term alliances.
 * Protection
   * Similar to how @Heriptik does his server where there is no raiding and the plugin acts as a towny/clans mix.

### CODE REVIEW

**Comment by Kittycraft** [comment]
## Massivecraft factions commands 
All the major ones should be usable to allow from a smooth transition onto a sponge server for server owners. Many others can just be omitted from this list.
- [ ] /f the factions base command
- [ ] /f list [page=1] list all factions
- [ ] /f f, faction [faction=you] show faction information
- [ ] /f player [player=you] show player information
- [ ] /f join <faction> [player=you] join faction
- [ ] /f leave leave your faction
- [ ] /f home [faction=you] teleport to faction home
- [ ] /f map [on/off=once] show territory map
- [ ] /f status [page=1] [faction=you] see faction member power and online activity
- [ ] /f create <name> create new faction
- [ ] /f name <new name> [faction=you] set faction name
- [ ] /f desc <desc> change faction description
- [ ] /f motd [new=read] faction motd
- [ ] /f sethome [faction=you] set the faction home
- [ ] /f unsethome [faction=you] unset faction home
- [ ] /f i,inv,invite a,add <players> invite player
- [ ] /f i,inv,invite r,remove <players/all> revoke an invite
- [ ] /f i,inv,invite l,list [page=1] [faction=you] list invited players
- [ ] /f kick <player> kick player from faction
- [ ] /f title <player> <title> set player title
- [ ] /f promote <player> promote lesser members in your faction
- [ ] /f demote <player> demote lesser members in your faction
- [ ] /f officer <player> make player officer
- [ ] /f leader <player> [faction=you] set leader for faction
- [ ] /f money manage faction money
- [ ] /f money b,balance [faction=you] show faction money
- [ ] /f money d,deposit <amount> [faction=you] deposit to faction
- [ ] /f money w,withdraw <amount> [faction=you] withdraw from faction
- [ ] /f money ff <amount> <faction> <faction> transfer faction –> faction
- [ ] /f money fp <amount> <faction> <player> transfer faction –> player
- [ ] /f money pf <amount> <player> <faction> transfer player –> faction
- [ ] /f sc,seechunk [active=toggle] see the chunk you stand in
- [ ] /f sco,seechunkold see the chunk you stand in
- [ ] /f tt,territorytitles [on|off=toggle] toggle territory titles
- [ ] /f claim claim faction territory1111 *<- Exact quote*
- [ ] /f claim o,one [faction=you] claim a single chunk
- [ ] /f claim a,auto [faction=you] claim as you walk around
- [ ] /f claim f,fill [faction=you] claim by filling
- [ ] /f claim s,square [radius=1] [faction=you] claim by square and radius
- [ ] /f claim c,circle [radius=1] [faction=you] claim by circle and radius
- [ ] /f claim all <all|map> <faction> <newfaction> claim all faction land
- [ ] /f unclaim unclaim faction territory
- [ ] /f unclaim o,one unclaim a single chunk
- [ ] /f unclaim a,auto unclaim as you walk around
- [ ] /f unclaim f,fill unclaim by filling
- [ ] /f unclaim s,square [radius=1] unclaim by square and radius
- [ ] /f unclaim c,circle [radius=1] unclaim by circle and radius
- [ ] /f unclaim all <all|map> <faction> unclaim all faction land
- [ ] /f access manage access
- [ ] /f access v,view view access
- [ ] /f access p,player <player> [yes/no=toggle] grant player access
- [ ] /f access f,faction <faction> [yes/no=toggle] grant faction access
- [ ] /f unstuck teleport to nearest wilderness
- [ ] /f ally <faction> set relation wish to another faction
- [ ] /f truce <faction> set relation wish to another faction
- [ ] /f neutral <faction> set relation wish to another faction
- [ ] /f enemy <faction> set relation wish to another faction
- [ ] /f perm set [perm=all] [relation=read] [yes/no=read] change faction permissions
- [ ] /f flag [faction=you] [flag=all] [yes/no=read] manage faction flags
- [ ] /f expansions list expansions
- [ ] /f tax Use FactionsTax
- [ ] /f tax i,info overview tax info
- [ ] /f tax f,faction [faction=you] faction tax info
- [ ] /f tax p,player [player=you] player tax info/
- [ ] /f tax s,set <amount|none> [default|rank|player|all=default] [faction=you] set tax
- [ ] /f tax run run taxation task
- [ ] /f tax v,version display plugin version
- [ ] /f dynmap Use FactionsDynmap
- [ ] /f dynmap v,version display plugin version
- [ ] /f admin [on/off=flip] enable adminmode
- [ ] /f disband [faction=you] disband faction
- [ ] /f powerboost <p|f|player|faction> <name> <#> set powerboost
- [ ] /f v,version display plugin version

**Comment by Kittycraft** [comment]
@Aquerr, I don't know if you have seen this pull request yet, but I am revisiting it now and I think it does not suit the goal of EagleFactions and is mostly just for my personal project of recreating Massivecraft factions on sponge (but with custom ranks).

New plan: 
Finish database support on Kittycraft/master -> change how permissions are implemented and saved to make it more logical -> finish permissions command -> finish connecting new permissions system to older flag system -> add progress from this branch (roughly) -> etc.

**Comment by Aquerr** [comment]
I was sick past few days but I got better now.

My thought with EF was to make something similar to Massivecraft's factions (or even a recreation). The problem is that last time when I played using Massivecraft's factions was something like 5-6 years ago or to be more precise, when MC's version was 1.6.4. Because of that, there are many features in Massivecraft's factions that I don't know about and I was trying to implement as much as I remember from 1.6.4.

The pull request you did looks absolutely fine. :)
As Eagle Factions is my first try with "plugin-coding" I understand that there are maaaaany things that can be improved or written better. 

I can merge this pull request if you will open it again. 

P.S. I had in mind making a second project of this (EF 2) to go a little bit further with my own ideas but as always, time won't let me, hah.

**Comment by Kittycraft** [comment]
I closed it because at this point, Eagle Factions has developed into it's own thing with unique features you would not be able to find in Massivecraft, such as the /f ally add <faction> and /f ally remove <faction> instead of /f ally <faction> and /f <neutral>. I wanted to preserve those features which made Eagle Factions unique while also adding the features from Massivecraft, but in the end it seemed like more effort than it was worth so I closed the pull request and went back to my fork of it where I have been slowly destroying everything that made Eagle Factions special so that I could add Massivecraft factions.

This is also my first time making a plugin, and factions is something I have been playing for years. When I saw there was no plugin that had all of the major features from Massivecraft factions on Sponge, I decided why not.

If you decide to create Eagle Factions 2, I would definitely help with that process.

Also if I reopened this now, only about a fourth of the commands have been converted (can't compile until they are all finished) and I don't know what other bugs would emerge once that is finished due to the dependency injection.

**Pull request closed without merging**
