### PR TITLE
Neutral Factions

### PR DESCRIPTION
**Pull request by ACPenguin**
Hey could you add the ability to be Neutral as a Faction? for players who don't want to be attacked

### CODE REVIEW

**Comment by Aquerr** [comment]
Do you have any idea how this should work?

I mean, I understand that the neutral faction should be „protected” from attacking (fighting and attacking with /f attack?) but I am having difficulties to imagine how such neutral faction should be turned on.

If I add a command for this which could be used by faction’s leader, they will be able to switch to neutral faction during fight and it will equal to cheat.

If I add a config node for this, then an admin will be able to set if factions should be treated as neutral by default (or being created as neutral factions).

On the other hand, all factions are currently treated like neutral factions. You can invite them to the alliance (then they cannot be attacked by you) or declare a war. So all factions are like neutral because you can do whatever you want with them.

Maybe the one that you are thinking of should be called pacifists’ faction?

**Comment by ACPenguin** [comment]
Yea something like that, i’ve just being trying to find a plugin so like maybe nations or factions can be large on a server, as im setting up a server using a map of the world but with flans.

So what im thinking is something like towny where you can have peaceful towns and alliances or maybe even everyone’s peaceful and then it takes time for someone to attack or go to war? Maybe like they’ll have to justify to go to war like in Hearts of Iron IV, where it could just take a couple of days irl before they can attack

Admittedly im just looking for a plugin where people aren’t always been raided but you can go to war with people

Also with the cheaty thing where faction leaders can just declare themselves peaceful could take some time or could be limited like in passive mode in GTA V if i remember correctly so they’ll have to wait a amount of time before they can


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MoonCodeing** [comment]
Can their be a Recruit Rank?, As of recruit members, they can't do anything, so members still can destroy/place, use blocks, and officers still having normal permissions to claim land, if I just turned off destroy/place blocks for members, then they would need officer to place/destroy blocks, which that is dangerous as they can claim some land that you don't want them too, so I can just make recruit not being able to destroy/place blocks which would be nice. Thx If you ever add this in.

**Comment by Aquerr** [comment]
@MoonCodeing Recruiter rank sounds good. Personally I have to say it was bothering me tool that there is no recruiter rank.

I will try to add this as soon as possible and maybe a few more flaga to Flags Command. :)

**Pull request merged**
